from pathlib import Path

from loguru import logger
from tqdm import tqdm
import typer

import numpy as np
from matplotlib import pyplot as plt

from hyperspectral_image_road_segmentation.config import FIGURES_DIR, PROCESSED_DATA_DIR

app = typer.Typer()


@app.command()
def main(
    # ---- REPLACE DEFAULT PATHS AS APPROPRIATE ----
    # input_path: Path = PROCESSED_DATA_DIR / "dataset.csv",
    # output_path: Path = FIGURES_DIR / "plot.png",
    # -----------------------------------------
):
    # # ---- REPLACE THIS WITH YOUR OWN CODE ----
    # logger.info("Generating plot from data...")
    # for i in tqdm(range(10), total=10):
    #     if i == 5:
    #         logger.info("Something happened for iteration 5.")
    # logger.success("Plot generation complete.")
    # # -----------------------------------------

    train_loss = np.load('reports\\figures\\train_loss.npy')
    plt.plot(train_loss)

    val_loss = np.load('reports\\figures\\val_loss.npy')
    plt.plot(val_loss)
    plt.show()

    # Things we should also try to plot:

    # Total number of samples

    # Image dimensions distribution (height × width)

    # Average pixel-level distribution <= this is import to know the class distribution
    # % road pixels
    # % background pixels

    # Eventually we will have some npy files generated by predict.py


if __name__ == "__main__":
    app()
